services:
  apache:
    image: 'detlearsom/httpd'
    volumes:
      - '$PWD/config:/usr/local/apache2/htdocs'    
    ports:
      - "80:80"
    networks:
      - capture

  siege:
    image: 'detlearsom/siege'
    command: siege -c${CONCURRENT_THREADS} -r${REQUESTS} -v http://apache
    networks:
      - capture

  tcpdump_apache:
    image: 'detlearsom/tcpdump'
    command: dump-040-httpd ${CAPTURETIME} ${SCENARIO} ${REPNUM}
    volumes:
      - '$PWD/data:/data'
    network_mode: "service:apache"
    depends_on:
      - apache


  tcpdump_siege:
    image: 'detlearsom/tcpdump'
    command: dump-040-siege ${CAPTURETIME} ${SCENARIO} ${REPNUM}
    volumes:
      - '$PWD/data:/data'
    network_mode: "service:siege"
    depends_on:
      - siege

networks:
  capture:
    driver: "bridge"
