services:
  sql:
    image: 'mysql/mysql-server'
    container_name: mysql
    ports:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes: 
      - $PWD/sql-share:/home/share/
      - $PWD/sql-settings/my.cnf:/etc/my.cnf
      #command: /home/share/sql_share.sh password
    networks:
      capture:
        ipv4_address: 172.16.238.22
  
  apache:
    image: 'detlearsom/php'
    container_name: apachephp
    volumes:
       - '$PWD/config:/var/www/html'
    ports:
      - "80:80"
    networks:
      capture:
        ipv4_address: 172.16.238.20

  admin:
    image: 'detlearsom/python'
    command: python /usr/share/scripts/populate_userlist.py
    #command: sleep 1000
    volumes:
      - '$PWD/admin-share:/usr/share/scripts'
    networks:
      - capture

  tcpdump_apache:
    image: 'detlearsom/tcpdump-trunc'
    command: 140-apache ${CAPTURETIME} ${SCENARIO} ${REPNUM}
    volumes:
      - '$PWD/data:/data'
    network_mode: "service:apache"
    depends_on:
      - apache

  tcpdump_admin:
    image: 'detlearsom/tcpdump-trunc'
    command: 140-admin ${CAPTURETIME} ${SCENARIO} ${REPNUM}
    volumes:
      - '$PWD/data:/data'
    network_mode: "service:admin"
    depends_on:
      - admin

  tcpdump_sql:
    image: 'detlearsom/tcpdump-trunc'
    command: 140-sql ${CAPTURETIME} ${SCENARIO} ${REPNUM}
    volumes:
      - '$PWD/data:/data'
    network_mode: "service:sql"
    depends_on:
      - sql


networks:
  capture:
    driver: "bridge"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
