version: '2'
services:
  nginx:
    image: vulhub/openssl:1.0.1c-with-nginx
    volumes:
     - ./www:/var/www/html
    ports:
     - "8080:80"
     - "8443:443"
    networks:
      capture:
        ipv4_address: 172.16.233.15


  msf:
    image: 'detlearsom/msfconsole'
    #command: sleep 1000
    command: /var/lib/msf_script.sh $DURATION
    volumes:
      - '$PWD/msf_share:/var/lib'
    networks:
      capture:
        ipv4_address: 172.16.233.20


  tcpdump_nginx:
    image: 'detlearsom/tcpdump'
    command: dump-120-heartbleed ${CAPTURETIME} ${SCENARIO} ${REPNUM}
    volumes:
      - '$PWD/data:/data'
    network_mode: "service:nginx"
    depends_on:
      - nginx

  tcpdump_msf:
    image: 'detlearsom/tcpdump'
    command: dump-120-attacker ${CAPTURETIME} ${SCENARIO} ${REPNUM}
    volumes:
      - '$PWD/data:/data'
    network_mode: "service:msf"
    depends_on:
      - msf

networks:
  capture:
    driver: "bridge"
    ipam:
      driver: default
      config:
      - subnet: 172.16.233.0/24
        gateway: 172.16.233.1
