services:
  nginx:
    image: 'nginx:1.13.8-alpine'
    ports:
      - "8080:80"
    networks:
      - capture

  tcpdump_nginx:
    image: 'detlearsom/tcpdump'
    command: dump-020-nginx-server ${CAPTURETIME} ${SCENARIO} ${REPNUM}
    volumes:
      - '${DATADIR}:/data'
    network_mode: "service:nginx"
    depends_on:
      - nginx

  siege:
    image: 'detlearsom/siege'
    command: siege -c${CONCURRENT_THREADS} -r${REQUESTS} -v http://nginx
#    command: tail -F anything
    networks:
      - capture
    depends_on:
      - nginx

  tcpdump_siege:
    image: 'detlearsom/tcpdump'
    command: dump-020-siege ${CAPTURETIME} ${SCENARIO} ${REPNUM}
    volumes:
      - '${DATADIR}:/data'
    network_mode: "service:siege"
    depends_on:
      - siege

networks:
  capture:
    driver: "bridge"
