version: '3'

services:
  nginx_host:
    image: 'detlearsom/nginx-rtmp'
    ports:
      - '1935:1935'
      - '8081:8080'
    networks:
      capture:
        ipv4_address: 172.26.5.2

  streamer:
    image: 'detlearsom/ffmpeg'
    command: /usr/share/scripts/start_stream.sh
    #command: sleep 1000
    volumes:
      - '$PWD/streamer-share:/usr/share/'
    networks:
      - capture
    depends_on:
      - nginx_host

  viewer:
    image: 'detlearsom/rtmpdump'
    command: /usr/share/scripts/watch_stream.sh
    #command: sleep 1000
    volumes:
      - '$PWD/viewer-share:/usr/share/scripts'
    networks:
      - capture
    depends_on:
      - streamer

  tcpdump_nginx_host:
    image: 'detlearsom/tcpdump'
    command: dump-240-nginx ${CAPTURETIME} ${SCENARIO} ${REPNUM}
    volumes:
      - '$PWD/data:/data'
    network_mode: "service:nginx_host"
    depends_on:
      - nginx_host

  tcpdump_streamer:
    image: 'detlearsom/tcpdump'
    command: dump-240-streamer ${CAPTURETIME} ${SCENARIO} ${REPNUM}
    volumes:
      - '$PWD/data:/data'
    network_mode: "service:streamer"
    depends_on:
      - streamer

  tcpdump_viewer:
    image: 'detlearsom/tcpdump'
    command: dump-240-viewer ${CAPTURETIME} ${SCENARIO} ${REPNUM}
    volumes:
      - '$PWD/data:/data'
    network_mode: "service:viewer"
    depends_on:
      - viewer

networks:
  capture:
    driver: "bridge"
    ipam:
      driver: default
      config:
      - subnet: 172.26.5.0/24
        gateway: 172.26.5.1

