version: '3'
services:
  nginx:
    image: 'nginx:1.13.8-alpine'
    ports:
      - 8443:443
      - 8080:80
    volumes:
      - $PWD/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - $PWD/conf:/usr/share/nginx/html
      - $PWD/conf/ssl:/etc/ssl
    networks:
      capture:
        ipv4_address: 172.16.236.15

  wget_80:
    image: 'detlearsom/wget'
    command: watch -n 1 wget "http://nginx" -P /data
    depends_on:
      - nginx
    volumes:
      - "$PWD/data:/data"
      - "$PWD/conf/ssl:/etc/ssl"
    networks:
      capture:
        ipv4_address: 172.16.236.38

  wget_443:
    image: 'detlearsom/wget'
    command: watch -n 1 wget --ca-certificate=/etc/ssl/nginx.crt "https://nginx:443" -P /data
    depends_on:
      - nginx
    volumes:
      - "$PWD/data:/data"
      - "$PWD/conf/ssl:/etc/ssl"
    networks:
      capture:
        ipv4_address: 172.16.236.40

  tcpdump_nginx:
    image: 'detlearsom/tcpdump'
    command: dump-022-nginx-server ${CAPTURETIME} ${SCENARIO} ${REPNUM}
    volumes:
      - '${DATADIR}:/data'
    network_mode: "service:nginx"
    depends_on:
      - nginx

  tcpdump_wget_80:
    image: 'detlearsom/tcpdump'
    command: dump-022-wget_http ${CAPTURETIME} ${SCENARIO} ${REPNUM}
    volumes:
      - '${DATADIR}:/data'
    network_mode: "service:wget_80"
    depends_on:
      - wget_80


  tcpdump_wget_443:
    image: 'detlearsom/tcpdump'
    command: dump-022-wget_443 ${CAPTURETIME} ${SCENARIO} ${REPNUM}
    volumes:
      - '${DATADIR}:/data'
    network_mode: "service:wget_443"
    depends_on:
      - wget_443

networks:
  capture:
    driver: "bridge"
    ipam:
      driver: default
      config:
      - subnet: 172.16.236.0/24
        gateway: 172.16.236.1



