services:
  apache:
    image: 'httpd'
    volumes:
      - '$PWD/config/ssl/:/usr/local/apache2/conf'
      - '$PWD/config:/usr/local/apache2/htdocs'    
      - '$PWD/config/extra/httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf'
    ports:
      - "80:80"
      - "443:443"
    networks:
      capture:
        ipv4_address: 172.16.238.15

  wget_80:
    image: 'detlearsom/wget'
    command: watch -n 1 wget "http://apache" -P /data/downloaded
    depends_on:
      - apache
    volumes:
      - "$PWD/data:/data"
      - "$PWD/config/ssl:/etc/ssl"
    networks:
      capture:
        ipv4_address: 172.16.238.38

  wget_443:
    image: 'detlearsom/wget'
    command: watch -n 1 wget --ca-certificate=/etc/ssl/server.crt "https://apache:443" -P /data/downloaded
    depends_on:
      - apache
    volumes:
      - "$PWD/data:/data"
      - "$PWD/config/ssl:/etc/ssl"
    networks:
      capture:
        ipv4_address: 172.16.238.40

  tcpdump_apache:
    image: 'detlearsom/tcpdump'
    command: dump-042-apache ${CAPTURETIME} ${SCENARIO} ${REPNUM}
    volumes:
      - '${DATADIR}:/data'
    network_mode: "service:apache"
    depends_on:
      - apache


  tcpdump_wget_80:
    image: 'detlearsom/tcpdump'
    command: dump-042-wget_http ${CAPTURETIME} ${SCENARIO} ${REPNUM}
    volumes:
      - '${DATADIR}:/data'
    network_mode: "service:wget_80"
    depends_on:
      - wget_80


  tcpdump_wget_443:
    image: 'detlearsom/tcpdump'
    command: dump-042-wget_https ${CAPTURETIME} ${SCENARIO} ${REPNUM}
    volumes:
      - '${DATADIR}:/data'
    network_mode: "service:wget_443"
    depends_on:
      - wget_443

networks:
  capture:
    driver: "bridge"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1

