version: '3'
services:
  apache:
    image: 'httpd'
    volumes:
      - '$PWD/config:/usr/local/apache2/htdocs'
    networks:
      - capture

  wget:
    image: 'detlearsom/wget'
    command: watch -n 1 wget --recursive --page-requisites --html-extension --convert-links "http://apache" -P /data
    volumes:
      - "$PWD/data:/data"
    networks:
      - capture

  tcpdump_apache:
    image: 'detlearsom/tcpdump'
    command: dump-041-apache ${CAPTURETIME} ${SCENARIO} ${REPNUM}
    volumes:
      - '${DATADIR}:/data'
    network_mode: "service:apache"
    depends_on:
      - apache


  tcpdump_wget:
    image: 'detlearsom/tcpdump'
    command: dump-041-wget ${CAPTURETIME} ${SCENARIO} ${REPNUM}
    volumes:
      - '${DATADIR}:/data'
    network_mode: "service:wget"
    depends_on:
      - wget

networks:
  capture:
    driver: "bridge"
