version: '2'

services:
  apache:
    image: 'detlearsom/xxe'
    volumes:
       - '$PWD/config:/var/www/html'
    ports:
      - "80:80"
    networks:
      capture:
        ipv4_address: 172.16.238.20


  attacker:
    image: 'detlearsom/python'
    command: python /usr/share/scripts/attack$SCENARIO.py
#    command: sleep 1000
    volumes:
      - '$PWD/attacker-share:/usr/share/scripts'
    networks:
      - capture

  tcpdump_attacker:
    image: 'detlearsom/tcpdump'
    command: dump-260-attacker ${CAPTURETIME} ${SCENARIO} ${REPNUM}
    volumes:
      - '$PWD/data:/data'
    network_mode: "service:attacker"
    depends_on:
      - attacker

  tcpdump_apache:
    image: 'detlearsom/tcpdump'
    command: dump-260-server ${CAPTURETIME} ${SCENARIO} ${REPNUM}
    volumes:
      - '$PWD/data:/data'
    network_mode: "service:apache"
    depends_on:
      - apache


networks:
  capture:
    driver: "bridge"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
